name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]
    branches: [ main ]

jobs:
  cleanup-preview:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Surge CLI
      run: npm install -g surge
      
    - name: Delete preview deployment
      run: |
        export SURGE_DOMAIN="pr-${{ github.event.number }}-craig-test.surge.sh"
        surge teardown $SURGE_DOMAIN --token ${{ secrets.SURGE_TOKEN }}
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        
    - name: Comment PR
      uses: actions/github-script@v7
      with:
        script: |
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          
          const botComment = comments.find(comment => 
            comment.user.type === 'Bot' && 
            comment.body.includes('Preview deployment')
          );
          
          if (botComment) {
            const body = `## 🚀 Preview deployment
            
            ~~Your changes have been deployed to a preview environment~~
            
            **Preview deployment has been cleaned up** since this PR was closed.`;
            
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: body
            });
          }