name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

jobs:
  cleanup-preview:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        
    - name: Delete preview deployment
      run: |
        # Remove PR directory if it exists
        if [ -d "pr-${{ github.event.number }}" ]; then
          rm -rf "pr-${{ github.event.number }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Cleanup PR #${{ github.event.number }} preview" || exit 0
          git push
        fi
        
    - name: Comment PR
      uses: actions/github-script@v7
      with:
        script: |
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          
          const botComment = comments.find(comment => 
            comment.user.type === 'Bot' && 
            comment.body.includes('Preview deployment')
          );
          
          if (botComment) {
            const body = `## 🚀 Preview deployment
            
            ~~Your changes have been deployed to a preview environment~~
            
            **Preview deployment has been cleaned up** since this PR was closed.`;
            
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: body
            });
          }